/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NovaRequisicaoRouteImport } from './routes/nova-requisicao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RequisicoesRouteImport } from './routes/requisicoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRequisicaoRoute = NovaRequisicaoRouteImport.update({
  id: '/nova-requisicao',
  path: '/nova-requisicao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisicoesRoute = RequisicoesRouteImport.update({
  id: '/requisicoes',
  path: '/requisicoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/nova-requisicao': typeof NovaRequisicaoRoute
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/requisicoes': typeof RequisicoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/nova-requisicao': typeof NovaRequisicaoRoute
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/requisicoes': typeof RequisicoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/nova-requisicao': typeof NovaRequisicaoRoute
  '/perfil': typeof PerfilRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/requisicoes': typeof RequisicoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contratos'
    | '/dashboard'
    | '/nova-requisicao'
    | '/perfil'
    | '/produtos'
    | '/relatorios'
    | '/requisicoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contratos'
    | '/dashboard'
    | '/nova-requisicao'
    | '/perfil'
    | '/produtos'
    | '/relatorios'
    | '/requisicoes'
  id:
    | '__root__'
    | '/'
    | '/contratos'
    | '/dashboard'
    | '/nova-requisicao'
    | '/perfil'
    | '/produtos'
    | '/relatorios'
    | '/requisicoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContratosRoute: typeof ContratosRoute
  DashboardRoute: typeof DashboardRoute
  NovaRequisicaoRoute: typeof NovaRequisicaoRoute
  PerfilRoute: typeof PerfilRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RequisicoesRoute: typeof RequisicoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-requisicao': {
      id: '/nova-requisicao'
      path: '/nova-requisicao'
      fullPath: '/nova-requisicao'
      preLoaderRoute: typeof NovaRequisicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisicoes': {
      id: '/requisicoes'
      path: '/requisicoes'
      fullPath: '/requisicoes'
      preLoaderRoute: typeof RequisicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContratosRoute: ContratosRoute,
  DashboardRoute: DashboardRoute,
  NovaRequisicaoRoute: NovaRequisicaoRoute,
  PerfilRoute: PerfilRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  RequisicoesRoute: RequisicoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
